<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class AdminSaveCategoryRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => 'required|unique:categories|alpha|max:15'
        ];
    }

    public function attributes()
    {
//        return parent::attributes(); // TODO: Change the autogenerated stub
        return ['name' => 'category name'];
    }

    public function messages()
    {
//        return parent::messages(); // TODO: Change the autogenerated stub
        return ['name.required' => 'The category name is required.'];
    }
}
